# Yahoo Fantasy API Credentials
# These credentials are saved locally and will persist between sessions
[yahoo]
consumer_key = "dj0yJmk9MTJPUUpsREhpd1F4JmQ9WVdrOU1tbFNUVmhWVFVjbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PTVk"
consumer_secret = "fd54e033a23ac09e8de6f52286aaf64b3a000333"
# Access tokens will be added automatically after OAuth flow
access_token = ""
access_token_secret = ""

